apiVersion: v1
kind: Namespace
metadata:
  name: kubenav
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubenav
  namespace: kubenav
  labels:
    app.kubernetes.io/name: kubenav
    app.kubernetes.io/instance: kubenav
  annotations: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubenav
  namespace: kubenav
  labels:
    app.kubernetes.io/name: kubenav
    app.kubernetes.io/instance: kubenav
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubenav
  namespace: kubenav
  labels:
    app.kubernetes.io/name: kubenav
    app.kubernetes.io/instance: kubenav
subjects:
  - kind: ServiceAccount
    name: kubenav
    namespace: kubenav
roleRef:
  kind: ClusterRole
  name: kubenav
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenav
  namespace: kubenav
  labels:
    app.kubernetes.io/name: kubenav
    app.kubernetes.io/instance: kubenav
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubenav
      app.kubernetes.io/instance: kubenav
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubenav
        app.kubernetes.io/instance: kubenav
    spec:
      serviceAccountName: kubenav
      securityContext: {}
      containers:
        - name: kubenav
          securityContext: {}
          image: "kubenav/kubenav:3.1.0"
          imagePullPolicy: IfNotPresent
          args:
            - --incluster
          ports:
            - name: http
              containerPort: 14122
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kubenav
  namespace: kubenav
  labels:
    app.kubernetes.io/name: kubenav
    app.kubernetes.io/instance: kubenav
spec:
  type: ClusterIP
  ports:
    - port: 14122
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kubenav
    app.kubernetes.io/instance: kubenav
